### ISSUE TITLE
Wallet button unresponsive

### ISSUE THREAD

**Issue by tratteo** [Siamango/siamango-website#6]
Cannot disconnect the wallet anymore. When clicking on the wallet button when the wallet is connected, nothing happens

**Comment by Guizzz** [comment]
What page does it happen on? Home or Collective?

**Comment by tratteo** [comment]
Both

**Comment by tratteo** [comment]
@Guizzz is this fixed?

**Comment by Guizzz** [comment]
Yes, I forgot to close the issue
